// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using polywatchcore;

#nullable disable

namespace polywatchcore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GDELTEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("AverageTone")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("GoldsteinScale")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRootEvent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuadClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalArticlesAtUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMentionsAtUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSourcesAtUpdate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GDELTEvents");
                });

            modelBuilder.Entity("GDELTEvent", b =>
                {
                    b.OwnsOne("CAMEOActorGeodata", "ActionGeodata", b1 =>
                        {
                            b1.Property<string>("GDELTEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ADM1Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ADM2Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FeatureID")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("GeoName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("GeoType")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<float>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("GDELTEventId");

                            b1.ToTable("GDELTEvents");

                            b1.WithOwner()
                                .HasForeignKey("GDELTEventId");
                        });

                    b.OwnsOne("CAMEOActor", "Actor1", b1 =>
                        {
                            b1.Property<string>("GDELTEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EthnicCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("KnownGroupCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReligionCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReligionSubgroupCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeCodeA")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeCodeB")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeCodeC")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("GDELTEventId");

                            b1.ToTable("GDELTEvents");

                            b1.WithOwner()
                                .HasForeignKey("GDELTEventId");
                        });

                    b.OwnsOne("CAMEOActorGeodata", "Actor1Geodata", b1 =>
                        {
                            b1.Property<string>("GDELTEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ADM1Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ADM2Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FeatureID")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("GeoName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("GeoType")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<float>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("GDELTEventId");

                            b1.ToTable("GDELTEvents");

                            b1.WithOwner()
                                .HasForeignKey("GDELTEventId");
                        });

                    b.OwnsOne("CAMEOActor", "Actor2", b1 =>
                        {
                            b1.Property<string>("GDELTEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EthnicCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("KnownGroupCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReligionCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReligionSubgroupCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeCodeA")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeCodeB")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeCodeC")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("GDELTEventId");

                            b1.ToTable("GDELTEvents");

                            b1.WithOwner()
                                .HasForeignKey("GDELTEventId");
                        });

                    b.OwnsOne("CAMEOActorGeodata", "Actor2Geodata", b1 =>
                        {
                            b1.Property<string>("GDELTEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ADM1Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ADM2Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FeatureID")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("GeoName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("GeoType")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<float>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("GDELTEventId");

                            b1.ToTable("GDELTEvents");

                            b1.WithOwner()
                                .HasForeignKey("GDELTEventId");
                        });

                    b.Navigation("ActionGeodata");

                    b.Navigation("Actor1");

                    b.Navigation("Actor1Geodata");

                    b.Navigation("Actor2");

                    b.Navigation("Actor2Geodata");
                });
#pragma warning restore 612, 618
        }
    }
}
